---
security_updater_file: "/usr/local/bin/install_updates.sh"
security_updater_file_path: "{{ playbook_dir }}/roles/security/files/install_updates.sh"

docker_networks:
  - name: caddy_net
    driver: bridge
  - name: private_easy_gundam
    driver: bridge

# Caddy Container Configuration
caddy:
  container_name: caddy
  container_image: caddy:latest
  caddy_file_path: "{{ playbook_dir }}/roles/services/templates/Caddyfile.j2"
  data_volume: caddy_data
  config_volume: caddy_config
  networks:
    - name: caddy_net

projects_home: "/home/{{ username }}/projects"
redeploy_script: "{{ projects_home }}/redeploy.sh"
redeploy_script_path: "{{ playbook_dir }}/roles/services/files/redeploy.sh"
redeploy_cron_script: "{{ projects_home }}/webhook_cron.sh"

applications:
  # Webhook Container Configuration
  - container_name: webhook
    container_hostname: webhook
    container_port: 9000
    dockerfile_path: "{{ playbook_dir }}/roles/services/files"
    dockerfile_name: Dockerfile_webhook
    data_volume: webhook_data
    networks:
      - name: caddy_net
    domain: "{{ webhook_domain }}"
    caddy_file_rule: "rewrite * /hooks{uri}"
    webhook_file_path: "{{ playbook_dir }}/roles/services/templates/hooks.j2"
    redeploy_cron_script_path: "{{ playbook_dir }}/roles/services/templates/webhook_cron.j2"
    host_named_pipe: "/home/{{ username }}/webhook_pipe"
    output_pipe: /output_pipe
    send_to_pipe_path: "{{ playbook_dir }}/roles/services/templates/send_to_pipe.j2"
  # Yacht Container Configuration
  - container_name: yacht
    container_hostname: yacht
    container_image: selfhostedpro/yacht:latest
    container_port: 8000
    data_volume: yacht_data
    networks:
      - name: caddy_net
    domain: "{{ yacht_domain }}"
  # PgAdmin Container Configuration
  - container_name: pgadmin
    container_hostname: pgadmin
    container_image: dpage/pgadmin4:latest
    container_port: 80
    data_volume: pgadmin_data
    networks:
      - name: caddy_net
    domain: "{{ pgadmin_domain }}"
  # Resume Container Configuration
  - container_name: resume
    container_hostname: resume
    container_port: 8080
    data_volume: resume_data
    networks:
      - name: caddy_net
    domain: "{{ resume_domain }}"
    repo_name: "{{ resume_repo_name }}"
  # # Easy Gundam Container Configuration
  # - container_name: easy-gundam
  #   container_hostname: easy-gundam
  #   container_port: 8080
  #   data_volume: easy-gundam_data
  #   networks:
  #     - name: caddy_net
  #   domain: "{{ easy_gundam_domain }}"
  # # Easy Gundam API Container Configuration
  # - container_name: easy-gundam-api
  #   container_hostname: easy-gundam-api
  #   container_image: directus/directus:latest
  #   container_port: 8055
  #   data_volume: easy-gundam-api_data
  #   networks:
  #     - name: caddy_net
  #     - name: private_easy_gundam
  #   domain: "{{ easy_gundam_api_domain }}"
  # Easy Gundam DB Container Configuration
  - container_name: easy-gundam-api-db
    container_hostname: easy-gundam-api-db
    container_image: postgres:latest
    container_port: 5432
    data_volume: easy-gundam-api-db_data
    networks:
      - name: private_easy_gundam
