---
# - name: Configure security
#   ansible.builtin.import_playbook: security.yml

# - name: Install packages
#   ansible.builtin.import_playbook: packages.yml

- name: Configure services
  ansible.builtin.import_playbook: services.yml
